[build]
builder = "nixpacks"
buildCommand = "npm install --legacy-peer-deps && npm run build"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_20", "nodePackages.pnpm"]

[deploy]
startCommand = "npm run start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
